export * from "./EditMovie";
export * from "./Genres";
export * from "./Graphql";
export * from "./Login";
export * from "./Manage";
export * from "./Movies";
export * from "./Movie";
export * from "./NotFound";
export * from "./Home";
